'use strict';
// Unit registry: future units provide name, maxDigits, createPool and format.
// Session/timing/keypad/scoring remain independent of the question generator.
const UNITS=Object.freeze({'single-multiplication':{name:{zh:'個位數乘法',en:'Single-digit multiplication'},maxDigits:2,createPool(){return Array.from({length:100},(_,i)=>({a:Math.floor(i/10),b:i%10,answer:Math.floor(i/10)*(i%10)}));},format(q){return `${q.a} × ${q.b}`;}}});
const unit=UNITS['single-multiplication'];
const copy={zh:{garden:'乘法小花園',eyebrow:"LET'S GROW · 每天進步一點點",unit:'單元 01',welcome:'小腦袋，<br>準備發芽！',intro:'選好時間和題數，按下開始。<br>點數字、送出答案，一起練乘法！',timeLabel:'每題想多久？',countLabel:'這次挑戰幾題？',setupNote:'0–9 隨機相乘，每題都不重複。<br>最後 3 秒會「叮、叮、叮」，右上角可關閉音效。',start:'開始挑戰',gentle:'答錯也沒關係，每一題都是新的練習。',pause:'Ⅱ 暫停',timeLeft:'這題還有',keypadTitle:'點數字，填入你的答案',submit:'送出答案 ✓',keyboardNote:'也可以用鍵盤：數字輸入 · Backspace 倒退 · Enter 送出',points:'分',again:'再挑戰一次 ↻',settings:'調整時間與題數',review:'一起看看每一題',paused:'休息一下',pauseNote:'時間已停住，準備好再繼續。<br>你的答案和進度都會保留。',resume:'繼續挑戰 →',quit:'結束這次，回到設定',sec:'秒',questions:'題',clear:'清除',erase:'倒退刪除',soundOn:'音效開',soundOff:'音效關',soundEnable:'開啟倒數音效',soundDisable:'關閉倒數音效',hint:'想一想，再點數字送出答案！',next:'下一題 →',finish:'看看成績 →',correct:'答對了！做得好！',timeout:'時間到！',wrong:'再練一次就更熟了！',done:'這題完成',allDone:'挑戰完成！',perfect:'全部答對，太棒了！',resultEncourage:'每一次練習，都讓你更熟練。',right:'答對',incorrect:'答錯',timedout:'超時',yourAnswer:'你的答案',noAnswer:'未作答',correctAnswer:'正確答案',keypad:'答案數字鍵盤'},en:{garden:'Multiplication Garden',eyebrow:"LET'S GROW · A LITTLE EVERY DAY",unit:'UNIT 01',welcome:'Little minds,<br>ready to grow!',intro:'Pick your time and question count.<br>Tap the numbers, then send your answer!',timeLabel:'Time for each question',countLabel:'How many questions?',setupNote:'Multiply numbers from 0–9. No repeated questions.<br>Hear a ding for each of the last 3 seconds. Sound is optional.',start:'Start challenge',gentle:'Mistakes are part of growing. Try your best!',pause:'Ⅱ Pause',timeLeft:'Time left',keypadTitle:'Tap the numbers to answer',submit:'Send answer ✓',keyboardNote:'Keyboard: numbers to type · Backspace to delete · Enter to send',points:'points',again:'Play again ↻',settings:'Change settings',review:'Let’s look at each question',paused:'Take a little break',pauseNote:'The timer is paused. Continue when you’re ready.<br>Your answer and progress are saved.',resume:'Keep going →',quit:'End this round & go to settings',sec:'s',questions:'Q',clear:'Clear',erase:'Delete last digit',soundOn:'Sound on',soundOff:'Sound off',soundEnable:'Turn on countdown sounds',soundDisable:'Turn off countdown sounds',hint:'Work it out, tap the numbers, then send!',next:'Next question →',finish:'See my score →',correct:'You got it! Well done!',timeout:'Time’s up!',wrong:'A little more practice helps!',done:'Question complete',allDone:'Challenge complete!',perfect:'All correct. Amazing!',resultEncourage:'Every little practice helps you grow.',right:'Correct',incorrect:'Incorrect',timedout:'Timed out',yourAnswer:'Your answer',noAnswer:'No answer',correctAnswer:'Correct answer',keypad:'Answer number keypad'}};
const $=id=>document.getElementById(id);let lang='zh',seconds=5,total=10,sound=true,phase='setup',questions=[],records=[],index=0,entry='',remaining=0,deadline=0,raf=0,lastTick=0,pausedPhase='',audioContext=null;const activeTones=new Set();
const t=key=>copy[lang][key];
function shuffle(items){const a=items.slice();for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]];}return a;}
function buildChoices(){ $('time-options').innerHTML=Array.from({length:8},(_,i)=>i+3).map(n=>`<button class="choice" data-seconds="${n}" aria-pressed="${n===seconds}">${n}<small>${t('sec')}</small></button>`).join('');$('count-options').innerHTML=[5,10,20,30,50].map(n=>`<button class="choice" data-count="${n}" aria-pressed="${n===total}">${n}<small>${t('questions')}</small></button>`).join(''); }
function buildKeypad(){ $('keypad').setAttribute('aria-label',t('keypad'));$('keypad').innerHTML=[1,2,3,4,5,6,7,8,9,'clear',0,'erase'].map(k=>`<button class="key ${typeof k==='string'?'utility':''}" data-key="${k}"${typeof k==='string'?` aria-label="${t(k)}"`:''}>${k==='clear'?t('clear'):k==='erase'?'<svg aria-hidden="true" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><path d="M9 5h12v14H9L2 12Z"/><path d="m12 9 6 6m0-6-6 6"/></svg>':k}</button>`).join(''); }
function updateSound(){ $('sound').setAttribute('aria-pressed',String(sound));$('sound').setAttribute('aria-label',t(sound?'soundDisable':'soundEnable'));$('sound-label').textContent=t(sound?'soundOn':'soundOff');$('sound-icon').textContent=sound?'♫':'♪̸'; }
function renderLanguage(){document.documentElement.lang=lang==='zh'?'zh-Hant':'en';document.title=unit.name[lang]+' | '+t('garden');document.querySelectorAll('[data-i18n]').forEach(e=>e.innerHTML=t(e.dataset.i18n));document.querySelectorAll('[data-lang]').forEach(e=>e.setAttribute('aria-pressed',String(e.dataset.lang===lang)));$('unit-title').textContent=unit.name[lang];buildChoices();buildKeypad();updateSound();if(['asking','feedback','paused'].includes(phase))renderQuestion();if(phase==='results')renderResults();}
function ensureAudio(){try{const C=window.AudioContext||window.webkitAudioContext;if(!C)return;if(!audioContext)audioContext=new C();if(audioContext.state==='suspended')audioContext.resume().catch(()=>{});}catch{}}
function silence(){activeTones.forEach(o=>{try{o.stop();}catch{}});activeTones.clear();}
function ding(){if(!sound||!audioContext||audioContext.state!=='running')return;const now=audioContext.currentTime;[880,1320].forEach((frequency,i)=>{const oscillator=audioContext.createOscillator(),gain=audioContext.createGain();oscillator.type='sine';oscillator.frequency.value=frequency;gain.gain.setValueAtTime(0,now);gain.gain.linearRampToValueAtTime(i?.035:.1,now+.008);gain.gain.exponentialRampToValueAtTime(.001,now+.32);oscillator.connect(gain);gain.connect(audioContext.destination);activeTones.add(oscillator);oscillator.onended=()=>{activeTones.delete(oscillator);oscillator.disconnect();gain.disconnect();};oscillator.start(now);oscillator.stop(now+.34);});}
function showScreen(name){['setup','play','results'].forEach(s=>$(s).hidden=s!==name);window.scrollTo({top:0,left:0,behavior:'instant'});}
function begin(){cancelAnimationFrame(raf);silence();if(sound)ensureAudio();questions=shuffle(unit.createPool()).slice(0,total);records=[];index=0;showScreen('play');newQuestion();$('equation').focus({preventScroll:true});}
function newQuestion(){phase='asking';entry='';remaining=seconds*1000;lastTick=seconds;deadline=performance.now()+remaining;renderQuestion();if(seconds<=3)ding();cancelAnimationFrame(raf);raf=requestAnimationFrame(tick);}
function tick(now){if(phase!=='asking')return;remaining=Math.max(0,deadline-now);renderTimer();const tickValue=Math.ceil(remaining/1000);if(tickValue!==lastTick){lastTick=tickValue;if(tickValue>0&&tickValue<=3)ding();}if(remaining<=0){settle(true);return;}raf=requestAnimationFrame(tick);}
function renderTimer(){const inFeedback=phase==='feedback'||phase==='paused'&&pausedPhase==='feedback';$('timer').textContent=inFeedback?'—':`${Math.ceil(remaining/1000)} ${t('sec')}`;$('timer-label').textContent=t(inFeedback?'done':'timeLeft');$('time-fill').style.transform=`scaleX(${Math.max(0,remaining/(seconds*1000))})`;const urgent=!inFeedback&&remaining<=3000;$('timer').classList.toggle('urgent',urgent);$('time-track').classList.toggle('urgent',urgent);}
function renderQuestion(){const q=questions[index];if(!q)return;const feedback=phase==='feedback'||phase==='paused'&&pausedPhase==='feedback';$('factor-a').textContent=q.a;$('factor-b').textContent=q.b;$('equation').setAttribute('aria-label',lang==='zh'?`${q.a} 乘以 ${q.b}`:`${q.a} times ${q.b}`);$('answer').textContent=entry||'?';$('answer').classList.toggle('empty',!entry);$('answer').setAttribute('aria-label',`${t('yourAnswer')}: ${entry||t('noAnswer')}`);$('progress-text').textContent=lang==='zh'?`第 ${index+1} / ${total} 題`:`Question ${index+1} of ${total}`;$('correct-count').textContent=`${t('right')} ${records.filter(r=>r.correct).length}`;$('progress-fill').style.width=`${records.length/total*100}%`;$('submit').hidden=feedback;$('submit').disabled=phase!=='asking'||entry==='';$('next').hidden=!feedback;$('next').textContent=t(index===total-1?'finish':'next');document.querySelectorAll('[data-key]').forEach(e=>e.disabled=phase!=='asking');$('feedback').className='feedback';if(feedback){const r=records[index];$('feedback').classList.add(r.correct?'correct':'incorrect');$('feedback').textContent=r.correct?t('correct'):`${t(r.timeout?'timeout':'wrong')} ${unit.format(q)} = ${q.answer}`;}else $('feedback').textContent=t('hint');renderTimer();}
function typeKey(key){if(phase!=='asking')return;if(performance.now()>=deadline){settle(true);return;}if(key==='clear')entry='';else if(key==='erase')entry=entry.slice(0,-1);else if(/^\d$/.test(String(key))&&entry.length<unit.maxDigits)entry=entry==='0'?String(key):entry+key;renderQuestion();}
function settle(timeout=false){if(phase!=='asking'||!timeout&&entry==='')return;const now=performance.now();timeout=timeout||now>=deadline;remaining=Math.max(0,deadline-now);cancelAnimationFrame(raf);silence();const q=questions[index];records.push({...q,input:entry,timeout,correct:!timeout&&entry!==''&&Number(entry)===q.answer});phase='feedback';renderQuestion();}
function next(){if(phase!=='feedback')return;if(index===total-1){phase='results';showScreen('results');renderResults();$('result-title').focus({preventScroll:true});}else{index++;newQuestion();}}
function pause(){if(!['asking','feedback'].includes(phase))return;pausedPhase=phase;if(phase==='asking'){remaining=Math.max(0,deadline-performance.now());if(remaining<=0){settle(true);pausedPhase='feedback';}}phase='paused';cancelAnimationFrame(raf);silence();renderQuestion();$('pause-dialog').showModal();}
function resume(){if(phase!=='paused')return;$('pause-dialog').close();phase=pausedPhase;if(sound)ensureAudio();if(phase==='asking'){deadline=performance.now()+remaining;lastTick=Math.ceil(remaining/1000);raf=requestAnimationFrame(tick);}renderQuestion();}
function goSetup(){cancelAnimationFrame(raf);silence();if($('pause-dialog').open)$('pause-dialog').close();phase='setup';showScreen('setup');buildChoices();$('start').focus({preventScroll:true});}
function renderResults(){const correct=records.filter(r=>r.correct).length,timedout=records.filter(r=>r.timeout).length;const score=Math.round(correct/total*100);$('score').textContent=score;$('result-title').textContent=t(correct===total?'perfect':'allDone');$('result-note').textContent=lang==='zh'?`${total} 題完成 · 每題 ${seconds} 秒。${t('resultEncourage')}`:`${total} questions · ${seconds}s each. ${t('resultEncourage')}`;$('stats').innerHTML=`<span>${t('right')} <strong>${correct}</strong></span><span>${t('incorrect')} <strong>${total-correct-timedout}</strong></span><span>${t('timedout')} <strong>${timedout}</strong></span>`;$('review-list').innerHTML=records.map((r,i)=>`<div class="review-item ${r.correct?'':'wrong'}"><div><span class="review-detail">${i+1}.</span> <span class="review-equation">${unit.format(r)} = ${r.answer}</span></div><div class="review-detail">${r.correct?'✓ '+t('right'):r.timeout?t('timeout'):t('yourAnswer')+': '+r.input}${r.timeout&&r.input?'<br>'+t('yourAnswer')+': '+r.input:''}</div></div>`).join('');}
$('time-options').addEventListener('click',e=>{const b=e.target.closest('[data-seconds]');if(b&&phase==='setup'){seconds=Number(b.dataset.seconds);buildChoices();}});$('count-options').addEventListener('click',e=>{const b=e.target.closest('[data-count]');if(b&&phase==='setup'){total=Number(b.dataset.count);buildChoices();}});document.querySelectorAll('[data-lang]').forEach(b=>b.addEventListener('click',()=>{lang=b.dataset.lang;renderLanguage();}));$('sound').addEventListener('click',()=>{sound=!sound;if(sound){ensureAudio();}else silence();updateSound();});$('start').addEventListener('click',begin);$('again').addEventListener('click',begin);$('settings').addEventListener('click',goSetup);$('keypad').addEventListener('click',e=>{const b=e.target.closest('[data-key]');if(b)typeKey(b.dataset.key);});$('submit').addEventListener('click',()=>settle());$('next').addEventListener('click',next);$('pause').addEventListener('click',pause);$('resume').addEventListener('click',resume);$('quit').addEventListener('click',goSetup);$('pause-dialog').addEventListener('cancel',e=>{e.preventDefault();resume();});
document.addEventListener('keydown',e=>{if(e.ctrlKey||e.metaKey||e.altKey||e.repeat)return;if(phase==='asking'&&(/^[0-9]$/.test(e.key)||['Backspace','Delete'].includes(e.key))){e.preventDefault();typeKey(e.key==='Backspace'?'erase':e.key==='Delete'?'clear':e.key);}else if(e.key==='Enter'&&phase==='asking'&&(document.activeElement?.tagName!=='BUTTON'||document.activeElement?.closest('#keypad'))){e.preventDefault();settle();}else if(e.key==='Escape'&&['asking','feedback'].includes(phase)){e.preventDefault();pause();}});
document.addEventListener('visibilitychange',()=>{if(document.hidden)pause();});if(document.modelContext?.registerTool){try{Promise.resolve(document.modelContext.registerTool({name:'configure_multiplication_quiz',title:'Configure multiplication quiz',description:'Set the per-question timer and question count on the setup screen without starting the quiz.',inputSchema:{type:'object',properties:{seconds:{type:'integer',minimum:3,maximum:10},questions:{type:'integer',enum:[5,10,20,30,50]}},required:['seconds','questions'],additionalProperties:false},annotations:{readOnlyHint:false},execute(input){if(!input||!Number.isInteger(input.seconds)||input.seconds<3||input.seconds>10||![5,10,20,30,50].includes(input.questions))throw new Error('Invalid quiz settings');if(phase!=='setup')throw new Error('Return to setup before changing settings');seconds=input.seconds;total=input.questions;buildChoices();return {seconds,questions:total,screen:'setup'};}})).catch(()=>{});}catch{}}
window.addEventListener('pagehide',()=>{cancelAnimationFrame(raf);silence();});renderLanguage();
